name = "hexdocs_search"
version = "1.0.0"
target = "javascript"

[dependencies]
envoy = ">= 1.0.0 and < 2.0.0"
gleam_fetch = ">= 1.2.0 and < 2.0.0"
gleam_hexpm = ">= 3.0.0 and < 4.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_regexp = ">= 1.1.0 and < 2.0.0"
gleam_stdlib = ">= 0.54.0 and < 1.0.0"
grille_pain = ">= 1.1.0 and < 2.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
lustre_dev_tools = ">= 2.0.0 and < 3.0.0"
modem = ">= 2.0.0 and < 3.0.0"
snag = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[tools.lustre.dev]
host = "0.0.0.0"

[tools.lustre.build]
minify = true

[tools.lustre.html]
lang = "en"
title = "Hexdocs"
stylesheets = [
  { href = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" },
  { href = "https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" },
]
