name = "hexdocs_search"
version = "1.0.0"
target = "javascript"

[dependencies]
envoy = ">= 1.0.2 and < 2.0.0"
gleam_fetch = ">= 1.1.1 and < 2.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.54.0 and < 1.0.0"
grille_pain = ">= 1.1.2 and < 2.0.0"
lustre = ">= 4.6.4 and < 5.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
modem = ">= 2.0.1 and < 3.0.0"
snag = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
